/// <reference types="vite/client" />
/**
 * Layout Editor integration (generated by the Stake Layout Editor).
 *
 * `layoutOverrides.data.ts` is the single file the Layout Editor desktop tool
 * saves into: per-profile layout overrides plus editor-created elements. Both
 * are applied on top of the authored component values in the editor AND when
 * the game runs normally.
 *
 * Keep this file free of game logic — it only wires the override runtime and
 * exposes optional editor-only actions used to preview game states.
 */
import {
	loadLayoutOverrides,
	registerEditorGameHooks,
	registerGameLayout,
	wireSpawnedElements,
} from 'pixi-svelte';

import { layoutOverridesData } from './layoutOverrides.data';
import { stateLayoutDerived } from './stateLayout';
import { stateApp } from './stateApp';

loadLayoutOverrides(layoutOverridesData, () => stateLayoutDerived.layoutType());

// Register the game's fitted content frame. Responsive rules can position
// against its bounds and follow its scale, matching the frame used by the
// game's MainContainer. Adapt the getter if your project names it differently.
registerGameLayout(() => stateLayoutDerived.mainLayout());

// Instantiates elements created from the Layout Editor (saved in the data file)
// in editor sessions AND normal runs. No-op while the list is empty.
wireSpawnedElements({
	getApp: () => stateApp.pixiApplication,
	getLoadedAssets: () => stateApp.loadedAssets,
});

// Optional: publish real, uniquely labelled game containers as editor parent
// targets. This metadata only describes the existing Stake hierarchy; it does
// not create screen-scope or lifecycle behavior. The record key must match the
// Pixi `label` on the actual Container/MainContainer/FadeContainer.
//
// Optional editor-only actions can jump the game into layout-relevant states.
// Broadcast your game's own emitter events here, e.g.:
//   import { eventEmitter } from './eventEmitter';
//   registerEditorGameHooks({
//     parentTargets: {
//       gameContent: {
//         label: 'Game content',
//         description: 'Stake MainContainer game coordinates; mounted after loading.',
//         order: 10,
//       },
//     },
//     gameEvents: {
//       freeSpinCounterShow: () => eventEmitter.broadcast({ type: 'freeSpinCounterShow' }),
//     },
//   });
registerEditorGameHooks({ parentTargets: {}, gameEvents: {} });

// Hot-swap saved overrides while the dev server runs (used by the editor's Save).
if (import.meta.hot) {
	import.meta.hot.accept('./layoutOverrides.data', (mod) => {
		if (mod) {
			loadLayoutOverrides(mod.layoutOverridesData, () => stateLayoutDerived.layoutType());
		}
	});
}
